### PR TITLE
Success screen

### PR DESCRIPTION
**Pull request by tomneo2004**
[Trello task](https://trello.com/c/zzxcxHJh/112-success-screen)

### Component description
- Component for success screen

### Files location
- `Success.js`: `src/Success`
- `Success.module.scss`: `src/Success`

### Assets imported
- Guitar icon: `assets/SuccessScreenAssets/electric-guitar-success.svg`
- Go back icon : `assets/SuccessScreenAssets/back-btn-Icon-success.svg`

### Note
- No responsive for different size of screen since responsive is not in criteria. Future might need to make it responsive.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
@tomneo2004 So, it seems Travis test is failing. I look into it [here](https://travis-ci.org/zero-to-mastery/visual-music/builds/602843806?utm_source=github_status&utm_medium=notification)

I think the problem is this: `HTTP error 404 Not Found`. However this is a new error, and I'm not sure how to fix it.

**Comment by tomneo2004** [comment]
@ArnasDickus I am trying to fix this issue, as this is first time I have this problem.

**Review by ArnasDickus — APPROVED** [review]
Alright, everything works. However you should update your current branch with newest changes by running.

on development branch
`git fetch upstream` - get the newest changes
`git merge upstream/development` - get the newest changes to your development branch.

If working on a unique branch..
`git merge upstream/SuccessScreen` - get newest changes to Success Screen branch,

**Comment by ArnasDickus** [comment]
Also since I can't figure it out what's wrong with the Travis test. I will approve this PR regardless of travis testing.

**Pull request merged**
