### PR TITLE
cleaning repo

### PR DESCRIPTION
**Pull request by YogiHa**
Clean component dir by sending pics and loading spinners to 'assets', delete demo components of upload song to local-host and cut and paste some in 'units'.

clean App.js 

module out from sketch.js the current draw function for future adding more than one animation

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Travis [test](https://travis-ci.org/zero-to-mastery/visual-music/builds/623918315?utm_source=github_status&utm_medium=notification) is failing @YogiHa. Not sure why. Either way can't approve until Travis test passes.

**Comment by YogiHa** [comment]
It says that the build passes the 50 min limit (and cant be extended in free usage..) and crash.. :\

we can try to clear build cache and I'll do another commit and see if the next test will be on time

**Comment by YogiHa** [comment]
added { isFullSize } state in App.js and sent it as props both to sketch and player bar.

in sketch, canvas resize accords to that boolean.

in player bar, if the screen is full size, two event listeners determine if bar have opacity of 0 or 1 accords to mouse enter/leave

**Review by ArnasDickus — CHANGES_REQUESTED** [review]
Hello,
The full-screen button was intended to hide everything. So the visual-music logo, log out button and hamburger should also be hidden. Reappear after move mouse down.

Is this visualization effect was intended?
visualization-wierd

**Comment by YogiHa** [comment]
Added in redux store a "full-size" sector with both "isFullSize" and "isElementsShowed", and took the event listeners from playerBar to utils for import in App, TopNav and PlayerBar.

**Review by ArnasDickus — APPROVED** [review]

**Pull request merged**
