### PR TITLE
Player Bar component

### PR DESCRIPTION
**Pull request by Santishish**
# Pull Request for Player Bar

- I created an assets folder with the svg icons for the player bar
- Added the required fonts in the `index.html` file
- Created the Player Bar component and css file

I used the methods in `App.js` for the play/pause and file upload. The volume button, progress bar and time are decorative for now.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Hello, @Santishish I reviewed your code. Found a couple of problems:
1) The player bar is not mobile responsive.
player-bar-not-responsive
2) On the upload new song button, if I hover over the text cursor is no longer a pointer.
3) Buttons such as snapshot, and download, should have cursor pointer.
4) Buttons download, and snapshot, not aligned correctly compared to design, try in .player-bar-right .download using justify-content: space between instead of space-around.

That's about it. I will create a new task for the rest of the features for player bar.

**Comment by Santishish** [comment]
1. That's because of the Visualizer component, it caused me a lot of problems with the design (I think it has a fixed width of 900px). The bar is still not fully responsive, but I don't have a mobile version of the mockup. What I can do for now is to hide the song icon and some buttons.
2. A z-index would fix that.
3. I'm completely sure they have cursor pointer.
4. It already has space-between. Did you mean the opposite?

**Comment by ArnasDickus** [comment]
Hello @Santishish 
Due to [PR #20](https://github.com/zero-to-mastery/visual-music/pull/20) you need to update your PR. Sorry, for the inconvenience. 

1) Regarding mockup, from my understanding, if you don't have a mobile version mockup it's up to you to create it without mockup. I'm going to investigate further today in about 6 hours from now, whether the Visualizer component is responsible for not responsiveness because I suspect it might not be the case.
2) Could you add z-index?
3) That's weird going to look into it today.
4) Yes, my mistake.

**Comment by ArnasDickus** [comment]
Hello, @Santishish  I can confirm, that Visualizer is the problem, regarding the problem. I disabled all the css including with 900px width, however, I couldn't identify the exact problem. Removing Visualizer seems to solve, responsiveness

I suggest doing this: 
1) Comment out in App.js Visualizer, and all related to it code. import etc.
2) Also, I suggest not using the player bar as a footer. I don't think it wasn't intended for it to be a footer. Use simple div.

**Comment by Santishish** [comment]
Hi @ArnasDickus I made a new commit with the following changes:

- Added z-index to upload new song button.
- Changed space-between to space around in .player-bar-right .download
- Commented Visualizer component and import in `App.js`

However, the Visualizer component was also responsible of playing the loaded song.

**Comment by ArnasDickus** [comment]
Hello, @Santishish so if you fix conflicting files, I could approve this PR. Here's what you should do.
I suggest create a copy in case you overwrite something.

`git checkout development` - visit development branch
`git fetch upstream development` - get newest changes from development branch.
`git merge upstream/development` - merge development branch to your own local branch.
`git checkout player-bar` - visit your current branch
`git merge upstream/development` - merge development branch changes with your current changes. if you using visual studio you and there are conflicts you will have to deal with it manually. After that the usual
`git status`
`git add`
`git commit -m 'message here'`
`git push`

**Comment by ArnasDickus** [comment]
Hello @Santishish, how's it going?

**Comment by Santishish** [comment]
Hi @ArnasDickus I'm sorry to have kept you waiting, I was very busy this week.
Thank you for your help, I resolved the conflicts with files and changed a .css file I was using to a .scss one. Let me know if there is something else to do 😃

**Pull request merged**
